### ISSUE TITLE
新增的transformer层是与上一层共享参数吗？

### ISSUE THREAD

**Issue by CharlinChen** [TencentARC/LLaMA-Pro#16]
请问在此处：
https://github.com/TencentARC/LLaMA-Pro/blob/b8fbe8c764edc80124a6c3e5062360ab9f7543d9/scripts/block_expansion.py#L35
直接将上一层参数共享给了下一层，保存为huggingface的.safetensors文件时会提示layer.3.x和layer.4.x参数是共享的。
此处是否应该为：
``` python
output[k.replace(('layers.' + str(i) + '.'), ('layers.' + str(layer_cnt) + '.'))] = ckpt[k].clone()
```

**Comment by PenutChen** [comment]
@hills-code 不過我也覺得加上 `.clone()` 會比較符合論文的描述，即便在 Hugging Face 裡面的行為是正確的
