### ISSUE TITLE
关于论文中通用能力榜单几乎没有下降，部分反而有提升

### ISSUE THREAD

**Issue by bestpredicts** [TencentARC/LLaMA-Pro#31]
看论文里面增量时候语料 只有code和math，并不包含通用语料配比。在一些通用榜单 比如mmlu、TruthfulQA上面几乎没有下降，表示质疑？ 我这边试验的时候，冻结原始层增量预训练，比起原始模型在通用能力榜单还是出现了小幅度的下降，即使我的语料已经混入了一些通用的语料。

**Comment by bestpredicts** [comment]
我这边试验的结果是，冻结在做增量预训练的方法在通用能力上面会比不冻结下降的少。但是相比于base模型的一些通用能力榜单比如ceval cmmlu还是有明显的一个下降。

**Comment by tammypi** [comment]
> 看论文里面增量时候语料 只有code和math，并不包含通用语料配比。在一些通用榜单 比如mmlu、TruthfulQA上面几乎没有下降，表示质疑？ 我这边试验的时候，冻结原始层增量预训练，比起原始模型在通用能力榜单还是出现了小幅度的下降，即使我的语料已经混入了一些通用的语料。

请问后面是怎么解决的？
